# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bazar_bio_development

test:
  <<: *default
  database: bazar_bio_test

production:
  <<: *default
  database: <%= ENV.fetch("BACKEND_DATABASE_NAME") { "bazar_bio_production" } %>
  username: <%= ENV.fetch("BACKEND_DATABASE_USER") { "bazar_user" } %>
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("BACKEND_DATABASE_HOST") { "localhost" } %>


