import { Product, Category, Artisan, DeliveryZone } from '@/types';

export const ARTISANS: Record<string, Artisan> = {
  mama_jeanne: {
    id: 'artisan-1',
    name: 'Mama Jeanne',
    role: 'Artisane Perlière Traditionnelle',
    city: 'Yaoundé (Quartier Briqueterie)',
    region: 'Centre',
    bio: 'Tisseuse passionnée de perles de verre recyclées et perles bamiléké depuis plus de 25 ans. Chaque création honore le patrimoine ancestral camerounais.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    productsCount: 12,
    joinedYear: 2023,
  },
  papa_mbele: {
    id: 'artisan-2',
    name: 'Papa Mbele',
    role: 'Maître Sculpteur sur Bois & Bronze',
    city: 'Yaoundé / Foumban',
    region: 'Ouest & Centre',
    bio: 'Issu d\'une lignée de forgerons et sculpteurs traditionnels de Foumban. Il utilise exclusivement des chutes de bois noble récupérées et du bronze fondu à la cire perdue.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    productsCount: 8,
    joinedYear: 2022,
  },
  ferme_mfou: {
    id: 'artisan-3',
    name: 'Coopérative Maraîchers Verts de Mfou',
    role: 'Producteurs Agro-Écologiques',
    city: 'Mfou',
    region: 'Centre (à 22 km de Yaoundé)',
    bio: 'Collectif de 14 familles d\'agriculteurs pratiquant le maraîchage biologique sur compost végétal et paillage naturel. Zéro intrant chimique, récoltes du matin.',
    imageUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80',
    rating: 5.0,
    productsCount: 18,
    joinedYear: 2021,
  },
  ferme_obala: {
    id: 'artisan-4',
    name: 'Vergers Bio de la Lékié (Obala)',
    role: 'Arboriculture & Fruits Sains',
    city: 'Obala',
    region: 'Centre (à 38 km de Yaoundé)',
    bio: 'Spécialiste des agrumes, ananas pain de sucre et papayes solos cultivés sous ombrage naturel sans aucun traitement synthétique.',
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    productsCount: 15,
    joinedYear: 2022,
  },
  coop_karite: {
    id: 'artisan-5',
    name: 'GIC Femmes & Karité Authentique',
    role: 'Cosmétique Naturelle & Huiles Pressées',
    city: 'Yaoundé (Atelier Essos)',
    region: 'Centre',
    bio: 'Transformation artisanale de beurres végétaux bruts de karité, cacao camerounais et huile d\'avocat pressée à froid. 100% pur et sans conservateurs.',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    productsCount: 9,
    joinedYear: 2023,
  },
};

export const CATEGORIES: Category[] = [
  {
    id: 'cat-legumes',
    name: 'Légumes & Tubercules Bio',
    slug: 'legumes-bio',
    description: 'Feuilles traditionnelles, tomates de plein champ, carottes et tubercules récoltés le matin même à Mfou & Obala.',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    itemCount: 18,
    iconName: 'Leaf',
  },
  {
    id: 'cat-fruits',
    name: 'Fruits Tropicaux de Saison',
    slug: 'fruits-de-saison',
    description: 'Ananas pain de sucre, papayes solos, bananes plantains et agrumes mûris naturellement sur l\'arbre.',
    imageUrl: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=800&q=80',
    itemCount: 14,
    iconName: 'Sparkles',
  },
  {
    id: 'cat-epices',
    name: 'Épices & Aromates du Terroir',
    slug: 'epices-et-aromates',
    description: 'Poivre blanc de Penja certifié, gingembre sauvage, rondelles de Njansang et herbes fraîches aromatiques.',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    itemCount: 11,
    iconName: 'ShoppingBag',
  },
  {
    id: 'cat-soins',
    name: 'Cosmétiques & Soins Purs',
    slug: 'cosmetiques-naturels',
    description: 'Beurre de karité non raffiné, beurre de cacao cru, huiles végétales de baobab et savons artisanaux saponifiés à froid.',
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-548970e30370?auto=format&fit=crop&w=800&q=80',
    itemCount: 9,
    iconName: 'Sparkles',
  },
  {
    id: 'cat-bijoux',
    name: 'Bijoux & Artisanat d\'Art',
    slug: 'bijoux-artisanaux',
    description: 'Colliers en perles bamiléké, bracelets en bronze fondu et accessoires durables façonnés à la main par nos artisans.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    itemCount: 12,
    iconName: 'Package',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-carottes-mfou',
    name: 'Carottes Bio Fraîches de Mfou',
    slug: 'carottes-bio-mfou',
    categoryId: 'cat-legumes',
    categoryName: 'Légumes & Tubercules Bio',
    price: 1500,
    unit: 'Kilogramme',
    unitAbbr: 'kg',
    season: 'Toute l\'année',
    originCity: 'Mfou (Centre)',
    distanceKm: 22,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Feuille de Bananier',
      co2ReductionPercent: 78,
      plasticAvoidedGrams: 45,
    },
    badges: ['100% Bio', 'Circuit Court (<25km)', 'Zéro Plastique'],
    description: 'Carottes croquantes cultivées en pleine terre vivante à Mfou, sans engrais chimiques ni fongicides de synthèse. Récoltées le jour de la livraison pour une teneur maximale en nutriments et sucres naturels.',
    shortDescription: 'Croquantes, sucrées et récoltées le matin même à Mfou.',
    specifications: {
      'Mode de culture': 'Plein champ, compost végétal naturel',
      'Origine': 'Mfou, Région du Centre, Cameroun',
      'Conservation': '7 à 10 jours au frais',
      'Emballage': 'Ligature en fibres végétales de raphia',
    },
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1447175008436-054170c2e979?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 45,
    artisan: ARTISANS.ferme_mfou,
    rating: 4.9,
    reviewsCount: 38,
    isFeatured: true,
    isSubscriptionEligible: true,
  },
  {
    id: 'prod-poivrons-obala',
    name: 'Poivrons Panachés d\'Obala',
    slug: 'poivrons-panaches-obala',
    categoryId: 'cat-legumes',
    categoryName: 'Légumes & Tubercules Bio',
    price: 1800,
    unit: 'Kilogramme',
    unitAbbr: 'kg',
    season: 'Toute l\'année',
    originCity: 'Obala (Lékié)',
    distanceKm: 38,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: '100% Kraft Compostable',
      co2ReductionPercent: 72,
      plasticAvoidedGrams: 50,
    },
    badges: ['100% Bio', 'Riche en Vitamine C', 'Zéro Pesticide'],
    description: 'Mélange de poivrons verts, jaunes et rouges charnus, cultivés en agro-écologie dans les terres fertiles d\'Obala. Arôme intense et peau fine.',
    shortDescription: 'Doux, colorés et gorgés de soleil de la Lékié.',
    specifications: {
      'Origine': 'Obala, Cameroun',
      'Traitement': 'Purin d\'ortie et neem naturel',
      'Emballage': 'Sachet Kraft respirant biodégradable',
    },
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 30,
    artisan: ARTISANS.ferme_obala,
    rating: 4.8,
    reviewsCount: 24,
    isFeatured: true,
    isSubscriptionEligible: true,
  },
  {
    id: 'prod-ananas-sucre',
    name: 'Ananas Pain de Sucre Pur Bio',
    slug: 'ananas-pain-de-sucre',
    categoryId: 'cat-fruits',
    categoryName: 'Fruits Tropicaux de Saison',
    price: 1200,
    unit: 'Pièce',
    unitAbbr: 'pc',
    season: 'Toute l\'année',
    originCity: 'Nkolbisson (Yaoundé VII)',
    distanceKm: 14,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Feuille de Bananier',
      co2ReductionPercent: 88,
      plasticAvoidedGrams: 40,
    },
    badges: ['100% Bio', 'Ultra-Local (<15km)', 'Zéro Résidu'],
    description: 'Ananas pain de sucre à chair blanche très juteuse, fondant et naturellement très sucré. Aucun arrosage aux stimulants de floraison, mûri à son rythme naturel.',
    shortDescription: 'Cœur tendre et sucré, récolté mûr sur pied.',
    specifications: {
      'Variété': 'Pain de Sucre blanc',
      'Origine': 'Collines de Nkolbisson, Yaoundé',
      'Indice Brix': '15° - Sucre naturel élevé',
    },
    imageUrl: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 50,
    artisan: ARTISANS.ferme_mfou,
    rating: 5.0,
    reviewsCount: 52,
    isFeatured: true,
    isSubscriptionEligible: true,
  },
  {
    id: 'prod-poivre-penja',
    name: 'Poivre Blanc de Penja Bio (Grand Cru)',
    slug: 'poivre-blanc-penja-bio',
    categoryId: 'cat-epices',
    categoryName: 'Épices & Aromates du Terroir',
    price: 3500,
    unit: 'Bocal de 100g',
    unitAbbr: '100g',
    season: 'Toute l\'année',
    originCity: 'Penja (Moungo)',
    distanceKm: 210,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Bocal en Verre Réutilisable',
      co2ReductionPercent: 65,
      plasticAvoidedGrams: 60,
    },
    badges: ['IGP Certifié', 'Terroir Volcanique', 'Bocal Consigné'],
    description: 'Le célèbre poivre blanc de Penja, récolté à la main sur les sols volcaniques du Moungo puis lavé aux eaux de source naturelles. Arômes boisés, musqués et mentholés uniques au monde.',
    shortDescription: 'Le roi des épices camerounaises dans son bocal consigné en verre.',
    specifications: {
      'Conditionnement': 'Bocal en verre hermétique consigné (500 FCFA remboursés au retour)',
      'Label': 'Indication Géographique Protégée (IGP)',
      'Origine': 'Vallée de Penja, Cameroun',
    },
    imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 28,
    artisan: ARTISANS.mama_jeanne,
    rating: 5.0,
    reviewsCount: 41,
    isFeatured: true,
    isSubscriptionEligible: false,
  },
  {
    id: 'prod-karite-cacao',
    name: 'Baume Pur Karité Sauvage & Beurre de Cacao',
    slug: 'baume-karite-cacao-pur',
    categoryId: 'cat-soins',
    categoryName: 'Cosmétiques & Soins Purs',
    price: 4000,
    unit: 'Pot en Verre 150ml',
    unitAbbr: '150ml',
    season: 'Toute l\'année',
    originCity: 'Yaoundé (Essos)',
    distanceKm: 6,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Bocal en Verre Réutilisable',
      co2ReductionPercent: 85,
      plasticAvoidedGrams: 75,
    },
    badges: ['100% Végétal', 'Fait Main', 'Zéro Conservateur Chimique'],
    description: 'Soin nourrissant corps et cheveux obtenu par émulsion douce de beurre de karité brut de savane et de beurre de cacao pur pressé au Cameroun. Parfum gourmand 100% naturel de chocolat.',
    shortDescription: 'Nutrition intense pour peau et cheveux, 100% pur et comestible.',
    specifications: {
      'Ingrédients': 'Butyrospermum Parkii (Karité brut), Theobroma Cacao Seed Butter (Cacao pur)',
      'Origine': 'Atelier GIC Essos, Yaoundé',
      'Contenant': 'Pot en verre brun anti-UV réutilisable',
    },
    imageUrl: 'https://images.unsplash.com/photo-1608248597359-548970e30370?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1608248597359-548970e30370?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 20,
    artisan: ARTISANS.coop_karite,
    rating: 4.9,
    reviewsCount: 33,
    isFeatured: true,
    isSubscriptionEligible: true,
  },
  {
    id: 'prod-collier-bamileke',
    name: 'Collier Royal "Ndanba" en Perles d\'Art',
    slug: 'collier-perles-bamileke',
    categoryId: 'cat-bijoux',
    categoryName: 'Bijoux & Artisanat d\'Art',
    price: 12500,
    unit: 'Pièce Unique',
    unitAbbr: 'pc',
    season: 'Toute l\'année',
    originCity: 'Yaoundé (Briqueterie)',
    distanceKm: 4,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Pochon en Coton Bio',
      co2ReductionPercent: 92,
      plasticAvoidedGrams: 110,
    },
    badges: ['Pièce Unique', 'Fait Main', 'Matériaux Upcyclés'],
    description: 'Tissé minutieusement rang par rang par Mama Jeanne selon les motifs géométriques des chefferies bamiléké. Perles de verre traditionnelles et fermoir en laiton recyclé forgé.',
    shortDescription: 'Bijou d\'artisanat d\'art camerounais dans son pochon en coton bio.',
    specifications: {
      'Temps de confection': '8 heures de tissage manuel',
      'Matériaux': 'Perles de verre, fil de lin naturel ciré, laiton recyclé',
      'Artisane': 'Mama Jeanne (Yaoundé)',
    },
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 5,
    artisan: ARTISANS.mama_jeanne,
    rating: 5.0,
    reviewsCount: 19,
    isFeatured: true,
    isSubscriptionEligible: false,
  },
  {
    id: 'prod-avocats-sauvages',
    name: 'Avocats Beurre Sauvages du Centre',
    slug: 'avocats-beurre-sauvages',
    categoryId: 'cat-fruits',
    categoryName: 'Fruits Tropicaux de Saison',
    price: 2000,
    unit: 'Lot de 4 pièces',
    unitAbbr: 'lot de 4',
    season: 'Saison des pluies',
    originCity: 'Bafia (Mbam-et-Inoubou)',
    distanceKm: 120,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: 'Feuille de Bananier',
      co2ReductionPercent: 80,
      plasticAvoidedGrams: 35,
    },
    badges: ['100% Bio', 'Cueillette Sauvage', 'Chair Fondante'],
    description: 'Avocats beurre géants à chair onctueuse et crémeuse, récoltés sur de vieux arbres centenaires non traités à Bafia. Idéal en salade ou simplement avec une pincée de poivre de Penja.',
    shortDescription: 'Crémeux, riches en bonnes graisses et non traités.',
    specifications: {
      'Variété': 'Avocat Beurre Géant',
      'Origine': 'Vergers traditionnels de Bafia',
      'Maturité': 'Prêt à consommer sous 2 à 3 jours',
    },
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 25,
    artisan: ARTISANS.ferme_obala,
    rating: 4.8,
    reviewsCount: 29,
    isFeatured: false,
    isSubscriptionEligible: true,
  },
  {
    id: 'prod-gingembre-sauvage',
    name: 'Gingembre & Curcuma Frais de Bafia',
    slug: 'gingembre-curcuma-bafia',
    categoryId: 'cat-epices',
    categoryName: 'Épices & Aromates du Terroir',
    price: 1500,
    unit: '500 grammes',
    unitAbbr: '500g',
    season: 'Toute l\'année',
    originCity: 'Bafia',
    distanceKm: 120,
    ecoScore: 'A',
    ecoScoreDetails: {
      pesticideFree: true,
      packagingType: '100% Kraft Compostable',
      co2ReductionPercent: 75,
      plasticAvoidedGrams: 40,
    },
    badges: ['100% Bio', 'Anti-Inflammatoire Puissant', 'Fraîcheur Racines'],
    description: 'Racines de gingembre et de curcuma jaune d\'or fraîchement déterrées, débordantes de jus et de principe actif (curcumine/gingérol). Zéro traitement chimique de conservation.',
    shortDescription: 'Racines aromatiques puissantes pour infusions et cuisine saine.',
    specifications: {
      'Contenu': '250g Gingembre frais + 250g Curcuma frais',
      'Origine': 'Terres alluviales de Bafia',
    },
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
    ],
    stockQuantity: 35,
    artisan: ARTISANS.ferme_mfou,
    rating: 4.9,
    reviewsCount: 17,
    isFeatured: false,
    isSubscriptionEligible: true,
  },
];

export const DELIVERY_ZONES: DeliveryZone[] = [
  { id: 'zone-bastos', name: 'Bastos', city: 'Yaoundé', fee: 1500, estimatedDeliveryHours: '1h30 - 2h30' },
  { id: 'zone-omnisports', name: 'Omnisports / Essos', city: 'Yaoundé', fee: 1200, estimatedDeliveryHours: '1h00 - 2h00' },
  { id: 'zone-odza', name: 'Odza / Tropicana', city: 'Yaoundé', fee: 2000, estimatedDeliveryHours: '2h00 - 3h00' },
  { id: 'zone-mendong', name: 'Mendong / Simbock', city: 'Yaoundé', fee: 1500, estimatedDeliveryHours: '2h00 - 3h00' },
  { id: 'zone-biyem-assi', name: 'Biyem-Assi / Rond-Point Express', city: 'Yaoundé', fee: 1500, estimatedDeliveryHours: '1h30 - 2h30' },
  { id: 'zone-santa-barbara', name: 'Santa Barbara / Golf', city: 'Yaoundé', fee: 1500, estimatedDeliveryHours: '1h30 - 2h30' },
  { id: 'zone-mvan', name: 'Mvan / Nsam', city: 'Yaoundé', fee: 1800, estimatedDeliveryHours: '2h00 - 3h00' },
  { id: 'zone-melen', name: 'Melen / EMIA / Ngoa-Ekélé', city: 'Yaoundé', fee: 1000, estimatedDeliveryHours: '1h00 - 1h45' },
];

export const IMPACT_GLOBAL_STATS = {
  totalBioProduceKg: 2840,
  totalPlasticBagsAvoided: 1420,
  localFarmingFamiliesSupported: 24,
  co2SavedTons: 3.6,
  treesEquivalentPlanted: 145,
};
